# -*- coding: utf-8 -*-
"""
Created on Sun Oct  7 14:31:57 2018

@author: Yann
"""
import turtle
import numpy as np
from scipy import interpolate
def drawarrow(x,y,direction):
    if direction==180:
        turtle.begin_fill()
        turtle.goto(x,y-2.5)
        turtle.goto(x-10.0,y)
        turtle.goto(x,y+2.5)
        turtle.goto(x,y)
        turtle.end_fill()
        turtle.goto(x-10,y)
        turtle.seth(180)
    if direction== 270:
        turtle.begin_fill()
        turtle.goto(x+2.5,y)
        turtle.goto(x,y-10)
        turtle.goto(x-2.5,y)
        turtle.goto(x,y)
        turtle.end_fill()
        turtle.goto(x,y-10)
        turtle.seth(270)
def createcoor():
    turtle.fd(300)
    turtle.right(135)
    turtle.begin_fill()
    turtle.fd(10)
    turtle.right(135)
    turtle.fd(14)
    turtle.right(135)
    turtle.fd(10)
    turtle.end_fill()
    turtle.pu()
    turtle.goto(305,0)
    turtle.write("x")
    turtle.goto(0,0)
    turtle.seth(90)
    turtle.pd()
    turtle.fd(300)
    turtle.right(135)
    turtle.begin_fill()
    turtle.fd(10)
    turtle.right(135)
    turtle.fd(14)
    turtle.right(135)
    turtle.fd(10)
    turtle.end_fill()
    turtle.pu()
    turtle.goto(0,305)
    turtle.write("y")
x=np.array([-90,0,70,160,208,280,300])
y=np.array([0,150,60,180,132,260,300])
f=interpolate.interp1d(x,y,kind=5)
xnew=np.arange(20)
ynew=f(xnew)

createcoor()
turtle.goto(0,0)
turtle.pd()
for i in range(300):
    turtle.goto(i,f(i))

turtle.penup()
turtle.goto(15,27)
turtle.write("globales Minimum")
turtle.goto(192,112)
turtle.write("lokales Minimum")
turtle.color("red")
turtle.goto(280,f(280))
turtle.seth(180)
turtle.pd()
turtle.fd(10)
xn,yn=turtle.position()
drawarrow(xn,yn,180)
turtle.left(90)
turtle.goto(260,(f(260))+10)
xn,yn=turtle.position()
drawarrow(xn,yn,270)
turtle.right(90)
turtle.fd(10)
xn,yn=turtle.position()
drawarrow(xn,yn,180)
turtle.goto(240,(f(240))+10)
xn,yn=turtle.position()
drawarrow(xn,yn,270)
turtle.right(90)
turtle.fd(10)
xn,yn=turtle.position()
drawarrow(xn,yn,180)
turtle.goto(220,(f(220))+10)
xn,yn=turtle.position()
drawarrow(xn,yn,270)
turtle.pu()
turtle.goto(1000,1000)
turtle.done()
turtle.bye()
